title: Computer Network Security
description: Computer Network Security webbook
theme: just-the-docs

url: https://keshvadi.github.io/security/

aux_links:
  Computer Network Security: https://keshvadi.github.io/security/

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pmarsceill/just-the-docs
color_scheme: wider
aux_links:
  "Computer Network Security":
    - "https://keshvadi.github.io/security"
  "Dark Mode":
    - "#"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - vendor/bundle/
  - yarn.lock
