title: Computer Network Security
description: Computer Network Security webbook

# Use remote_theme for GitHub Pages
remote_theme: just-the-docs/just-the-docs

# Correct URL settings for GitHub Pages
url: "https://keshvadi.github.io"
baseurl: "/security"

# Theme settings
color_scheme: dark # Or 'light' / 'wider'
aux_links:
  "GitHub Repository":
    - "https://github.com/keshvadi/security"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - vendor/bundle/
  - yarn.lock